name: calabiyau_kanami
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  flutter_launcher_icons: ^0.14.4
  flutter_html: ^3.0.0
  html: ^0.15.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/background/

  fonts:
    - family: Loliti
      fonts:
      - asset: assets/fonts/llt.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/app_icon.png"

  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 256
